### ISSUE TITLE
Migrate to mongoDB

### ISSUE THREAD

**Issue by cruzj6** [cruzj6/UpcomingGames#8]

**Comment by taz77** [comment]
You want to use MongoDB?

I would suggest Redis.

**Comment by cruzj6** [comment]
Hmmm you were telling me about Redis, I only have exposure to mongoDB. I worry Redis is more complex than what Is needed. But then again that's just from my limited research...I'll have to do more research and see the pros and cons more clearly. Speed isn't a huge concern as I'm not storing large amounts of data...but I don't know what kinds of capability might be added later, so could be eventually. I'm going to do more learning on Redis before I say I'll use it for sure...

**Comment by taz77** [comment]
Mongo is very JSON friendly whereas Redis is a strict key/value store. In Redis you would store your values as a blob that is JSON. I will say that I have no idea what your data structure is. Mongo stores things as JSON objects. After running Mongo servers for four years, I get frustrated with their function for fallover. Then AWS introduces Redis support in their ElasticCache service. This allows me to run caching services and not maintain the server. Redis is 100% an open source project (this could be why AWS selected it).  Mongo is also awesome, I got a 2.1 million record MongoDB mirrored array across three nodes for four years without any data loss and it never slows down.... semantics.
